apiVersion: v1
kind: Service
metadata:
  name: load-balancer-with-https-cert
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "your-certificate-uuid-here"
spec:
  type: LoadBalancer
  selector:
    app: event-api
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
