apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
spec:
  selector:
    matchLabels:
      app: event-processor
  template:
    metadata:
      labels:
        app: event-processor
    spec:
      containers:
      - name: event-processor
        image: registry.digitalocean.com/your-unique-container-registry-name/processor:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: REDIS_ADDRESS
            value: "redis-service:6379"
          - name: REDIS_EVENT_QUEUE
            value: "events"
